name: vosktest1204
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.7.0 <3.0.0'

dependencies: 
  cupertino_icons: ^0.1.3
  logger: any
  flutter: 
    sdk: flutter
  vosk_flutter_plugin: 
    path: ../vosk-flutter/
  # vosk_flutter_plugin:
  #   git:
  #     url: https://github.com/bahasa-kita/wakeword-flutter.git
  #     ref: v1

dev_dependencies: 
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/models/
  uses-material-design: true

